### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by elitemantis** [geekydoc/android_device_l70pn#8]
After instal pico gapps i cant watch any yt video.. crashed every time when i select something to watch... crash to pulpit withou massage.

**Comment by meganukebmp** [comment]
Logcats

**Comment by i-marszi** [comment]
02-19 10:06:16.338 30997-31216/? E/YouTube: Bogus value in shared preferences for key MdxServerSelection value , returning default value.
                                            java.lang.IllegalArgumentException:  is not a constant in com.google.android.libraries.youtube.mdx.util.MdxServerSelection
                                                at java.lang.Enum.valueOf(Enum.java:200)
                                                at com.google.android.libraries.youtube.mdx.util.MdxServerSelection.valueOf(MdxServerSelection.java:7)
                                                at com.google.android.libraries.youtube.mdx.MdxInjector$10.create(MdxInjector.java:521)
                                                at com.google.android.libraries.youtube.mdx.MdxInjector$10.create(MdxInjector.java:513)
                                                at com.google.android.libraries.youtube.common.util.Lazy.get(Lazy.java:136)
                                                at com.google.android.libraries.youtube.mdx.innertube.MdxWatchNextServiceRequestDecorator.decorate(MdxWatchNextServiceRequestDecorator.java:22)
                                                at com.google.android.libraries.youtube.innertube.services.WatchNextService.newRequest(WatchNextService.java:173)
                                                at com.google.android.libraries.youtube.player.net.WatchNextFetcher.requestWatchData(WatchNextFetcher.java:68)
                                                at com.google.android.libraries.youtube.player.sequencer.WatchNextSequencer$RequestWatchAndPlaybackRunnable.requestWatchNext(WatchNextSequencer.java:17047)
                                                at com.google.android.libraries.youtube.player.sequencer.WatchNextSequencer$RequestWatchAndPlaybackRunnable.run(WatchNextSequencer.java:720)
                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                at com.google.android.libraries.youtube.common.util.PriorityThreadFactory$1.run(PriorityThreadFactory.java:40)
                                                at java.lang.Thread.run(Thread.java:818)

**Comment by geekydoc** [comment]
Fixed. GPU driver problem. Closed
